# https://hub.docker.com/_/mysql
version: '3.1'

services:
  db:
    image: mysql:8.1.0
    container_name: mysql_for_local_development
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "carrot"
      MYSQL_ROOT_PASSWORD: "test"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci