spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carrot
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # By using ddl-auto, we can create an initial database
      ddl-auto: create
    properties:
      hibernate:
        #  show_sql: true ( Do not use it, show_sql will print log by using printer )
        format_sql: true
        # Instead of this, we can use @BatchSize, but highly recommended to use it globally
        default_batch_fetch_size: 100

logging:
  level:
    # Unlike show_sql, sql is supposed to be printed by logging
    org.hibernate.SQL: debug